import {createKeywordToken, createToken, SubhutiCreateTokenGroupType} from "../../subhuti/struct/SubhutiCreateToken";
import {Es6TokenName} from "../es6/old/Es6Tokens";

export const Es5TokensName = {
    // Keywords
    VarTok: 'VarTok',
    BreakTok: 'BreakTok',
    DoTok: 'DoTok',
    InstanceOfTok: 'InstanceOfTok',
    TypeofTok: 'TypeofTok',
    CaseTok: 'CaseTok',
    ElseTok: 'ElseTok',
    NewTok: 'NewTok',
    CatchTok: 'CatchTok',
    FinallyTok: 'FinallyTok',
    ReturnTok: 'ReturnTok',
    VoidTok: 'VoidTok',
    ContinueTok: 'ContinueTok',
    ForTok: 'ForTok',
    SwitchTok: 'SwitchTok',
    WhileTok: 'WhileTok',
    DebuggerTok: 'DebuggerTok',
    FunctionTok: 'FunctionTok',
    ThisTok: 'ThisTok',
    WithTok: 'WithTok',
    DefaultTok: 'DefaultTok',
    IfTok: 'IfTok',
    ThrowTok: 'ThrowTok',
    DeleteTok: 'DeleteTok',
    InTok: 'InTok',
    TryTok: 'TryTok',
    SuperTok: 'SuperTok',
    NullLiteral: 'NullLiteral',
    TrueTok: 'TrueTok',
    FalseTok: 'FalseTok',
    // Identifiers
    IdentifierName: 'IdentifierName',
    SetTok: 'SetTok',
    GetTok: 'GetTok',
    // Punctuators
    LBrace: 'LBrace',
    RBrace: 'RBrace',
    LParen: 'LParen',
    RParen: 'RParen',
    LBracket: 'LBracket',
    RBracket: 'RBracket',
    Dot: 'Dot',
    Semicolon: 'Semicolon',
    Comma: 'Comma',
    // Operators
    PlusPlus: 'PlusPlus',
    MinusMinus: 'MinusMinus',
    Ampersand: 'Ampersand',
    VerticalBar: 'VerticalBar',
    Circumflex: 'Circumflex',
    Exclamation: 'Exclamation',
    Tilde: 'Tilde',
    AmpersandAmpersand: 'AmpersandAmpersand',
    VerticalBarVerticalBar: 'VerticalBarVerticalBar',
    Question: 'Question',
    Colon: 'Colon',
    Asterisk: 'Asterisk',
    Slash: 'Slash',
    Percent: 'Percent',
    Plus: 'Plus',
    Minus: 'Minus',
    LessLess: 'LessLess',
    MoreMore: 'MoreMore',
    MoreMoreMore: 'MoreMoreMore',
    Less: 'Less',
    More: 'More',
    LessEq: 'LessEq',
    MoreEq: 'MoreEq',
    EqEq: 'EqEq',
    NotEq: 'NotEq',
    EqEqEq: 'EqEqEq',
    NotEqEq: 'NotEqEq',
    Eq: 'Eq',
    PlusEq: 'PlusEq',
    MinusEq: 'MinusEq',
    AsteriskEq: 'AsteriskEq',
    PercentEq: 'PercentEq',
    LessLessEq: 'LessLessEq',
    MoreMoreEq: 'MoreMoreEq',
    MoreMoreMoreEq: 'MoreMoreMoreEq',
    AmpersandEq: 'AmpersandEq',
    VerticalBarEq: 'VerticalBarEq',
    CircumflexEq: 'CircumflexEq',
    SlashEq: 'SlashEq',
    // Literals
    NumericLiteral: 'NumericLiteral',
    StringLiteral: 'StringLiteral',
    RegularExpressionLiteral: 'RegularExpressionLiteral',
    Whitespace: 'Whitespace'
};
export const es5TokensObj = {
    // Keywords
    VarTok: createKeywordToken(Es5TokensName.VarTok, "var"),
    BreakTok: createKeywordToken(Es5TokensName.BreakTok, "break"),
    DoTok: createKeywordToken(Es5TokensName.DoTok, "do"),
    InstanceOfTok: createKeywordToken(Es5TokensName.InstanceOfTok, "instanceof"),
    TypeofTok: createKeywordToken(Es5TokensName.TypeofTok, "typeof"),
    CaseTok: createKeywordToken(Es5TokensName.CaseTok, "case"),
    ElseTok: createKeywordToken(Es5TokensName.ElseTok, "else"),
    NewTok: createKeywordToken(Es5TokensName.NewTok, "new"),
    CatchTok: createKeywordToken(Es5TokensName.CatchTok, "catch"),
    FinallyTok: createKeywordToken(Es5TokensName.FinallyTok, "finally"),
    ReturnTok: createKeywordToken(Es5TokensName.ReturnTok, "return"),
    VoidTok: createKeywordToken(Es5TokensName.VoidTok, "void"),
    ContinueTok: createKeywordToken(Es5TokensName.ContinueTok, "continue"),
    ForTok: createKeywordToken(Es5TokensName.ForTok, "for"),
    SwitchTok: createKeywordToken(Es5TokensName.SwitchTok, "switch"),
    WhileTok: createKeywordToken(Es5TokensName.WhileTok, "while"),
    DebuggerTok: createKeywordToken(Es5TokensName.DebuggerTok, "debugger"),
    FunctionTok: createKeywordToken(Es5TokensName.FunctionTok, "function"),
    ThisTok: createKeywordToken(Es5TokensName.ThisTok, "this"),
    WithTok: createKeywordToken(Es5TokensName.WithTok, "with"),
    DefaultTok: createKeywordToken(Es5TokensName.DefaultTok, "default"),
    IfTok: createKeywordToken(Es5TokensName.IfTok, "if"),
    ThrowTok: createKeywordToken(Es5TokensName.ThrowTok, "throw"),
    DeleteTok: createKeywordToken(Es5TokensName.DeleteTok, "delete"),
    InTok: createKeywordToken(Es5TokensName.InTok, "in"),
    TryTok: createKeywordToken(Es5TokensName.TryTok, "try"),
    SuperTok: createKeywordToken(Es5TokensName.SuperTok, "super"),
    NullLiteral: createKeywordToken(Es5TokensName.NullLiteral, "null"),
    TrueTok: createKeywordToken(Es5TokensName.TrueTok, "true"),
    FalseTok: createKeywordToken(Es5TokensName.FalseTok, "false"),
    SetTok: createKeywordToken(Es5TokensName.SetTok, "set"),
    GetTok: createKeywordToken(Es5TokensName.GetTok, "get"),

    // Punctuators
    LBrace: createToken({name: Es5TokensName.LBrace, pattern: /\{/}),
    RBrace: createToken({name: Es5TokensName.RBrace, pattern: /}/}),
    LParen: createToken({name: Es5TokensName.LParen, pattern: /\(/}),
    RParen: createToken({name: Es5TokensName.RParen, pattern: /\)/}),
    LBracket: createToken({name: Es5TokensName.LBracket, pattern: /\[/}),
    RBracket: createToken({name: Es5TokensName.RBracket, pattern: /]/}),
    Dot: createToken({name: Es5TokensName.Dot, pattern: /\./}),
    Semicolon: createToken({name: Es5TokensName.Semicolon, pattern: /;/}),
    Comma: createToken({name: Es5TokensName.Comma, pattern: /,/}),
    // Operators
    PlusPlus: createToken({name: Es5TokensName.PlusPlus, pattern: /\+\+/}),
    MinusMinus: createToken({name: Es5TokensName.MinusMinus, pattern: /--/}),
    Ampersand: createToken({name: Es5TokensName.Ampersand, pattern: /&/}),
    VerticalBar: createToken({name: Es5TokensName.VerticalBar, pattern: /\|/}),
    Circumflex: createToken({name: Es5TokensName.Circumflex, pattern: /\^/}),
    Exclamation: createToken({name: Es5TokensName.Exclamation, pattern: /!/}),
    Tilde: createToken({name: Es5TokensName.Tilde, pattern: /~/}),
    AmpersandAmpersand: createToken({name: Es5TokensName.AmpersandAmpersand, pattern: /&&/}),
    VerticalBarVerticalBar: createToken({name: Es5TokensName.VerticalBarVerticalBar, pattern: /\|\|/}),
    Question: createToken({name: Es5TokensName.Question, pattern: /\?/}),
    Colon: createToken({name: Es5TokensName.Colon, pattern: /:/}),
    Asterisk: createToken({name: Es5TokensName.Asterisk, pattern: /\*/}),
    Slash: createToken({name: Es5TokensName.Slash, pattern: /\/\//}),
    Percent: createToken({name: Es5TokensName.Percent, pattern: /%/}),
    Plus: createToken({name: Es5TokensName.Plus, pattern: /\+/}),
    Minus: createToken({name: Es5TokensName.Minus, pattern: /-/}),
    LessLess: createToken({name: Es5TokensName.LessLess, pattern: /<</}),
    MoreMore: createToken({name: Es5TokensName.MoreMore, pattern: />>/}),
    MoreMoreMore: createToken({name: Es5TokensName.MoreMoreMore, pattern: />>>/}),
    Less: createToken({name: Es5TokensName.Less, pattern: /</}),
    More: createToken({name: Es5TokensName.More, pattern: />/}),
    LessEq: createToken({name: Es5TokensName.LessEq, pattern: /<=/}),
    MoreEq: createToken({name: Es5TokensName.MoreEq, pattern: />=/}),
    EqEq: createToken({name: Es5TokensName.EqEq, pattern: /==/}),
    NotEq: createToken({name: Es5TokensName.NotEq, pattern: /!=/}),
    EqEqEq: createToken({name: Es5TokensName.EqEqEq, pattern: /===/}),
    NotEqEq: createToken({name: Es5TokensName.NotEqEq, pattern: /!==/}),
    Eq: createToken({name: Es5TokensName.Eq, pattern: /=/}),
    PlusEq: createToken({name: Es5TokensName.PlusEq, pattern: /\+=/}),
    MinusEq: createToken({name: Es5TokensName.MinusEq, pattern: /-=/}),
    AsteriskEq: createToken({name: Es5TokensName.AsteriskEq, pattern: /\*=/}),
    PercentEq: createToken({name: Es5TokensName.PercentEq, pattern: /%=/}),
    LessLessEq: createToken({name: Es5TokensName.LessLessEq, pattern: /<<=/}),
    MoreMoreEq: createToken({name: Es5TokensName.MoreMoreEq, pattern: />>=/}),
    MoreMoreMoreEq: createToken({name: Es5TokensName.MoreMoreMoreEq, pattern: />>>=/}),
    AmpersandEq: createToken({name: Es5TokensName.AmpersandEq, pattern: /&=/}),
    VerticalBarEq: createToken({name: Es5TokensName.VerticalBarEq, pattern: /\|=/}),
    CircumflexEq: createToken({name: Es5TokensName.CircumflexEq, pattern: /\^=/}),
    SlashEq: createToken({name: Es5TokensName.SlashEq, pattern: /\/=/}),

    // Identifiers
    // Literals
    IdentifierName: createToken({name: Es5TokensName.IdentifierName, pattern: /[A-Za-z_$][A-Za-z0-9_$]*/}),
    NumericLiteral: createToken({name: Es5TokensName.NumericLiteral, pattern: /-?\d+(\.\d+)?/}),
    StringLiteral: createToken({name: Es5TokensName.StringLiteral, pattern: /(["'])((?:\\\1|(?:(?!\1|\n|\r).)*)*)\1/}),
    RegularExpressionLiteral: createToken({
        name: Es5TokensName.RegularExpressionLiteral,
        pattern: /\/(?:\\.|[^\\\/])+\/[gimuy]*/
    }),
    Whitespace: createToken({
        name: Es5TokensName.Whitespace,
        pattern: /\s+/,
        group: SubhutiCreateTokenGroupType.skip
    }),
};
export const es5Tokens = Object.values(es5TokensObj);
